#!/usr/bin/env python3
"""Write ``app/_build_metadata.py`` before ``uv build`` / Docker image layers.

Reads optional environment variables and regenerates :mod:`app._build_metadata`
so installs without a ``.git`` directory still expose accurate version and
commit via ``GET /v1/meta``:

* ``DOMESTI_EMBED_VERSION`` — package version string (for example ``0.1.0``).
* ``DOMESTI_EMBED_COMMIT`` — full or short git SHA (first 12 hex chars are kept).

If a variable is unset or empty, the corresponding field is written as an empty
string and :mod:`app.build_info` falls back to ``importlib.metadata``, then
``pyproject.toml``, then ``git`` as usual.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path


def _ensure_uv() -> None:
    """Re-exec under ``uv run`` if not already in the managed environment."""

    if os.environ.get("UV_ACTIVE") or "/.venv/" in (sys.executable or ""):
        return
    uv = shutil.which("uv")
    if uv:
        os.execv(uv, [uv, "run", sys.argv[0], *sys.argv[1:]])


def _normalize_embedded_commit(raw: str) -> str:
    token = raw.strip()
    if not token:
        return ""
    if len(token) > 12:
        return token[:12]
    return token


def _write_metadata_file(repo_root: Path, version: str, commit: str) -> None:
    path = repo_root / "app" / "_build_metadata.py"
    body = f'''"""Autogenerated by scripts/embed_build_metadata.py — do not hand-edit."""

from __future__ import annotations

EMBEDDED_COMMIT: str = {commit!r}
EMBEDDED_VERSION: str = {version!r}
'''
    path.write_text(body, encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    version = os.environ.get("DOMESTI_EMBED_VERSION", "").strip()
    commit_raw = os.environ.get("DOMESTI_EMBED_COMMIT", "").strip()
    commit = _normalize_embedded_commit(commit_raw)
    _write_metadata_file(repo_root, version, commit)


if __name__ == "__main__":
    _ensure_uv()
    main()
